In [4]:
import tensorflow as tf
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

import pickle
from sklearn.preprocessing import MinMaxScaler

In [5]:
data = pd.read_csv("/content/mpst_full_data.csv").iloc[ :5000  , 1:4].values



In [6]:
# retrieval fuction 
def getMovieAtIndex(i):
  return data[i, [0]][0]

def getIndexOfMovie(title):
  return np.where(data[ : , [0]] == title)[0][0]

print(getIndexOfMovie("I Know What You Did Last Summer"))

3573


In [7]:

# combining all important columns into a single vector 
def combine(arr):
  features = []
  for i in range(len(arr)):
    features.append(arr[i][0] + " " + arr[i][1] + " " + arr[i][2])
  return np.array(features) 

features = combine(data)




In [8]:
# tokenization 

cm = CountVectorizer()
tokens = cm.fit_transform(features)

cs = cosine_similarity(tokens)



In [9]:
title = input("Write the movie you want to find similar movies for ")
index = getIndexOfMovie(title)

Write the movie you want to find similar movies for Scarface


In [20]:
print(cs)
print(type(cs))
with open("cs.pkl", "wb") as f:
  f.write(pickle.dumps(cs))

[[1.         0.80139056 0.76187741 ... 0.80660372 0.82049307 0.81609745]
 [0.80139056 1.         0.62336466 ... 0.74822282 0.73583025 0.82955192]
 [0.76187741 0.62336466 1.         ... 0.75593014 0.74890681 0.67314608]
 ...
 [0.80660372 0.74822282 0.75593014 ... 1.         0.79286124 0.78413765]
 [0.82049307 0.73583025 0.74890681 ... 0.79286124 1.         0.77863819]
 [0.81609745 0.82955192 0.67314608 ... 0.78413765 0.77863819 1.        ]]
<class 'numpy.ndarray'>


In [13]:
Movie_Similarities = []
for i in range(len(cs)):
  Movie_Similarities.append((getMovieAtIndex(i), cs[index][i] * 100))
Movie_Similarities = sorted(Movie_Similarities, key=lambda x:x[1], reverse=True)

In [14]:
with open("rec.txt", "a") as f:
  for i in range(len(cs)):
    f.write(f"{Movie_Similarities[i][0]}: {Movie_Similarities[i][1]}%\n")

In [16]:
with open("confusion_matrix.pkl","wb") as f:
  f.write(pickle.dumps(cm))

with open("dataset.pkl", "wb") as f:
  f.write(pickle.dumps(data))